@Restaurants.API_HostAddress = http://localhost:5001
# For more info on HTTP files go to https://aka.ms/vs/httpfile
@bearerToken = CfDJ8Lxj95He-pdLmRiUX-TVBcG9hgWvA4Etp_YDyLKIKbmnymyyqrbscadNIvgbsd2AhAgSYKTNbCnghba5zNJZOZ4vBIRCrJeccFFojrIpTzdQIfuqvM0frOgWf94ZkDo2KR9cl5Uzv8QRj267CgT2zdCknwYw2zJPhpWkBSL6c3M9HH8Xd9na2eSb6Hxir8G1CUIjlISes21Ar4el_P7QD-q3MxoH9r6OMGcD-GJkpF85lD7ADeqcMIqWEn7VsJw-jvO41DKgtiGOrToveMq8xBXiRq8-A9_mm3RiBpfYYCf3tsTdYAw4kHNLT9Xr108ZwdMtOjVCJUfLYoOA3ldMwvY04RUxb5f9ThR88hxkUVUbWz2TjrtxHZIPJHBBPv89KfTeARIODE36f6xgR24rO2jFoi-NO7duaNlPPyu0ShWRwb7WslKCSLCKbeK2ZjIRcbHwfHPqtYMSao_tv6EEP60PH1W_Rz-mZb-D3yTq8hhfKCqV0_O5BfvtmYYSQh84znNKD1wSRH5h-BNK1IrGHOrR9Mf91RjR7LxV99PbnwF5DJficHyyBnF4d8ZRIX42LuokTdnVorfwQDQb4sKx1AdNQaLHWgceuWylq4Q3FcIKWCUrn1p0kOpNppxgSBECyOMAUzzszC0bvrgvE89MCe2u5IhTxC6YenPQw-69KjkhfheJpAr7vX6W_ZktPGicDo3E0mPjtwLZh6babmkwevT7-Dl-sk9HiuHBwsiz5keLFDSO4H6rQGUtZdjvp35VXBk-9dMow6hFuU0UfQIh2HeTiAbdSRzy9rJAFjzCwPmE

###

GET {{Restaurants.API_HostAddress}}/api/restaurants?SortBy=CategoryId&SortDirection=Descending
Authorization: Bearer {{bearerToken}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/17
Authorization: Bearer {{bearerToken}}

###
###

@id=4
GET {{Restaurants.API_HostAddress}}/api/Restaurants/{{id}}/dishes/13
Authorization: Bearer {{bearerToken}}


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
  "name": "Test Owner2 2",
  "description": "Fresh and authentic Japanese sushi",
  "hasDelivery": false,
  "categoryId":2,
  "contactEmail": "test2@email.jp",
  "contactNumber": "01228610700",
  "street": "456 Oak Avenue",
  "city": "Los Angeles",
  "postalCode": "90-013"
}
###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization:Bearer {{bearerToken}}

###

PUT {{Restaurants.API_HostAddress}}/api/restaurants/17
Content-Type: application/json
Authorization:Bearer {{bearerToken}}

{
  "id": 17,
  "name": "updated 1",
  "description": "Authentic Japanese sushi and sashimi made fresh daily with premium ingredients.",
  "hasDelivery": true,
  "categoryId": 3,
  "contactEmail": "contact2@kfc.com",
  "contactNumber": "01228616700",
  "street": "New St 78",
  "city": "Birmingham",
  "postalCode": "12-434",
  "category": null,
  "dishes": [],
  "createdAt": "2026-02-11T19:51:10.9372045",
  "updatedAt": null
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "user2@test.com",
  "password": "Test@123"
}
###

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "owner@test.com",
  "password": "Test@123"
}
###
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "admin@test.com",
  "password": "Test@123"
}
###
###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json
{
  "email": "admin@test.com",
  "password": "Test@123"
}
###

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Authorization: Bearer {{bearerToken}}
Content-Type: application/json
{
  "dateOfBirth": "2001-02-14",
  "nationality": "German"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Authorization: Bearer {{bearerToken}}
Content-Type: application/json

{
  "userEmail": "owner@test.com",
  "roleName": "Owner"
}

###


PUT {{Restaurants.API_HostAddress}}/api/restaurants/{id:int}
Content-Type: application/json

{
  //UpdateRestaurantCommand
}

###

GET {{Restaurants.API_HostAddress}}/api/identity/debug/claims
Authorization: Bearer {{bearerToken}}

###
